=== ldloler/LMSGI_DTD/Act2/cataleg.dtd
<!ELEMENT cataleg (llista_actors, llista_pelicules, llista_recomenacions_pelicules)>

<!-- llista d'actors -->
<!ELEMENT llista_actors (actor+)>
<!ELEMENT actor (nom, edat?)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT edat (#PCDATA)>
<!ATTLIST actor id ID #REQUIRED>

<!-- llista de pel·licules -->
<!ELEMENT llista_pelicules (pelicula+)>
<!ELEMENT pelicula (titol, director, any, actors)>
<!ATTLIST pelicula id ID #REQUIRED>
<!ELEMENT titol (#PCDATA)>
<!ATTLIST titol idioma CDATA #REQUIRED>
<!ELEMENT director (#PCDATA)>
<!ELEMENT any (#PCDATA)>
<!ELEMENT actors (actor_ref+)>
<!ELEMENT actor_ref EMPTY>
<!-- Referència de les IDs dels actors -->
<!ATTLIST actor_ref ref IDREF #REQUIRED>

<!-- Llista de recomenacions de pelicules-->
<!ELEMENT llista_recomenacions_pelicules (recomenacio*)>
<!ELEMENT recomenacio EMPTY>
<!-- Referència de les IDs de les pel·licules -->
<!ATTLIST recomenacio ref IDREF #REQUIRED>

=== ldloler/LMSGI_DTD/Act2/cataleg.xml
<!DOCTYPE cataleg SYSTEM "cataleg.dtd">
<cataleg>
    <!-- Actors -->
    <llista_actors>
        <actor id='a01'>
            <nom>Paco</nom>
            <edat>21</edat>
        </actor>

        <actor id='a02'>
            <nom>Marc</nom>
        </actor>
    </llista_actors>

    <!-- Pelis -->
    <llista_pelicules>
        <pelicula id='p01'>
            <titol idioma='Català'>Mec</titol>
            <director>Ernest</director>
            <any>2004</any>
            <actors>
                <actor_ref ref='a01'/>
            </actors>
        </pelicula>

        <pelicula id='p02'>
            <titol idioma='Català'>Mec</titol>
            <director>Ernest</director>
            <any>2004</any>
            <actors>
                <actor_ref ref='a01'/>
                <actor_ref ref='a02'/>
            </actors>
        </pelicula>
    </llista_pelicules>

    <!-- Recomenacions pelis -->
    <llista_recomenacions_pelicules>
        <!-- Pot estar tan buit com tenir varies recomenacions. -->
        <!-- <recomenacio ref="p01"/> -->
        <!-- <recomenacio ref="p02"/> -->
    </llista_recomenacions_pelicules>
</cataleg>
